[package]
name = "single_byte_xor_cipher"
version = "0.1.0"
authors = ["Bertie <berniesnell@gmail.com>"]
edition = "2018"

[dependencies]
xor = { path = "../xor" }
convert_hex_to_base64 = { path = "../convert_hex_to_base64" }
hex = "0.3.2"
