[workspace]

members = [
    "convert_hex_to_base64",
    "xor",
    "test/thingy",
    "single_byte_xor_cipher",
    "detect_single_xor",
    "repeating_xor",
    "break_repeating_xor",
    "decrypt_repeating"
]